### ISSUE TITLE
YASB doesn't work

### ISSUE THREAD

**Issue by AshbornXS** [lunar-os/windowsdesktop2#1]
made the installation just as instructed on the repo and them put your files as config but it simply didn't work, it just doesn't show anything

**Comment by lunar-os** [comment]
> made the installation just as instructed on the repo and them put your files as config but it simply didn't work, it just doesn't show anything

sorry hadn't removed that from my old repo. it doesn't use yasb it's just the default windows 11 taskbar with windhawk

**Comment by AshbornXS** [comment]
so how do u get that bar on bottom left?

**Comment by lunar-os** [comment]
> so how do u get that bar on bottom left?

it's the widget panel. enable the weather widget in taskbar. and u can see in the config that there is a location to a gif. change that to any image or gif u want

**Comment by AshbornXS** [comment]
hey, sorry to be reopening this issue just to ask a question but, I was tweaking your Taskbar Styler settings and I wanted the start button back, but when he's visible the image used on the widget gets put on his background in a almost pill shape, do u know if it's possible to fix that or u can only have one?

**Comment by lunar-os** [comment]
> e

Im not sure the exact target used to that in windhawk as I dont use the start button. However, using [UWPSpy ](https://github.com/m417z/UWPSpy) you can find the exact thing that you want to edit. set the process as explorer
