### ISSUE TITLE
how do i fix my weather thingy. it shows loading...

### ISSUE THREAD

**Issue by Nyxendoescode** [lunar-os/windowsdesktop2#2]
how do i fix this 
![Screenshot 2024-08-11 233543](https://github.com/user-attachments/assets/4da0ff89-53af-4307-8116-d61a5567c8b3)

**Comment by AshbornXS** [comment]
you need to config and run the [weather script](https://github.com/lunar-os/windowsdesktop/blob/main/Extras/weather_server)
