### ISSUE TITLE
Where is start menu logo?

### ISSUE THREAD

**Issue by LucasPC-hub** [lunar-os/windowsdesktop2#3]
You put `ImageSource="C:\Users\mrtsh\Downloads\asev3.gif" /` as a style for the start button , but i didnt find the file in this repo

**Comment by panicthescaredycat** [comment]
That's what i'm trying to figure out too, I don't think that's the start menu logo, I think that may be the Widgets on windows 11? I don't know anymore... I've spent like an hour trying to figure it out, placing my own image and shit, doesn't work...

**Comment by panicthescaredycat** [comment]
I fixed it, Go into Windows 11 Taskbar Styler > Settings > Scroll all the way down > You're going to remove the following > 

1. Windows.UI.Xaml.Controls.Grid#AugmentedEntryPointContentGrid
2. AdaptiveCards.Rendering.Uwp.WholeItemsPanel > Windows.UI.Xaml.Controls.TextBlock

Then the Widgets will show up again.
